### ISSUE TITLE
Question about adding buffer

### ISSUE THREAD

**Issue by MartinStokelj** [Liagson/ConcaveHullGenerator#1]
Is it possible to make bigger area, concave hull with buffer? 
So corner points needs to be moved more out for some buffer number...

**Comment by Liagson** [comment]
Yes. If I understand you correctly what you are asking can be solved in the **Init.cs** file by changing slightly this line:

`dot_list.Add(new Node(pseudorandom.Next(0, 100), pseudorandom.Next(0, 100), x));`

to something like this:
         
```
int hull_x_offset = 200; // Example number
int hull_width = 500; // Example number
int hull_y_offset = 300; // Example number
int hull_height = 600; // Example number
dot_list.Add(new Node(pseudorandom.Next(hull_x_offset , hull_x_offset  + hull_width ), pseudorandom.Next(hull_y_offset , hull_y_offset  + hull_height ), x));
```
Hope it helps :)

**Comment by MartinStokelj** [comment]
Sori for late response it was solved.

**Comment by MartinStokelj** [comment]
Can you add a parameter for setting buffer, with buffer i would like to tell how much out of current point the new returned points should be.
I hope the image will explain
![bufferExample](https://user-images.githubusercontent.com/30079270/66383848-0779ed80-e9be-11e9-9883-b96f6de22b9a.png)

**Comment by Liagson** [comment]
Hi Martin.
First of all, I'm afraid I'm not understanding your image. But if I understand you correctly, you want a new property inside the `Node` class with the distance of each point to a chosen coordinate? (Like in my image attached)
![bufferQuestion](https://user-images.githubusercontent.com/12009365/66420106-99f1af80-ea05-11e9-9f2e-7d4ba6f65c62.PNG)

**Note:** Green refers to the distance between points

**Comment by MartinStokelj** [comment]
I think you didn't understood corectly.
Concave hull returns outside points (dark blue line on my image) in array Hull.hull_concave_edges
I would like to set a buffer value (example 100 meters) for how much this points need to be moved more out (light blue line on my image), probably out of center would be correct method.
Currently I am using different library to achive that,

` List<List<IntPoint>> result = Clipper.OffsetPolygons(polygons, delta, JoinType.jtSquare); //delta is buffer`

**Comment by Liagson** [comment]
Yesterday I had some spare time to write a quick solution for your problem. You only need to add one extra static class and edit slightly the `Init.cs` file. You can read/comment the changes [here](https://gist.github.com/Liagson/df5bb487f1b0d73af1179cef092e84a7).

The result:
![bufferQuestion3](https://user-images.githubusercontent.com/12009365/66698604-a9137e80-ecdf-11e9-858a-b2059866dc35.PNG)

If you are curious about how I get the new point locations, I made a short explanation (my handwriting is terrible, I know):
![bufferQuestion2](https://user-images.githubusercontent.com/12009365/66698416-3b1a8780-ecde-11e9-9430-609a57e2a0bf.PNG)

After some consideration, for the moment I'm not going to add this feature to the ConcaveHullGenerator because I think it's out of scope. (But I thought it was fun to do, so I wrote it anyway)

I think this is what you were looking for. I hope :)

**Comment by MartinStokelj** [comment]
Yes, thank you very much.
