### ISSUE TITLE
LineIntersectionFunctions is giving me an error

### ISSUE THREAD

**Issue by hishamsasy** [Liagson/ConcaveHullGenerator#4]
First thank you for your amazing work

I am trying to use your library but i got this error, and I couldn't find this function anywhere

The name 'LineIntersectionFunctions' does not exist in the current context.

Am I missing something here ?

**Comment by Liagson** [comment]
Ooooops, my bad. I forgot to push that file to origin. The problem should be now fixed. Thanks for reporting this issue!!
Please, confirm me if it's working now fine.


**Note:** There have been some major changes in the code since yesterday. You can check Issue #3 to follow them (they shouldn't affect you much) I'll try to upload the new documentation as soon as I can.

**Comment by Liagson** [comment]
Looks like it's all working fine. I'm closing the issue.
